apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  interval: 10m
  timeout: 10m
  releaseName: tailscale-operator
  targetNamespace: tailscale
  storageNamespace: tailscale
  chart:
    spec:
      chart: tailscale-operator
      version: 1.102.3
      interval: 1h
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: tailscale
  valuesFrom:
    - kind: ConfigMap
      name: tailscale-operator-values
      valuesKey: values.yaml
  install:
    createNamespace: false
    crds: Create
    remediation:
      retries: 2
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 2
  test:
    enable: false
  driftDetection:
    mode: enabled
